from enum import Enum

class IntentType(str, Enum):
    """Classification of user intents"""
    GREETING = "GREETING"
    PATIENT_QUERY = "PATIENT_QUERY"
    CHECK_AVAILABILITY = "CHECK_AVAILABILITY"
    SEARCH_DOCTOR = "SEARCH_DOCTOR"
    BOOK_APPOINTMENT = "BOOK_APPOINTMENT"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT"
    VIEW_APPOINTMENTS = "VIEW_APPOINTMENTS"
    SYMPTOM_CHECK = "SYMPTOM_CHECK"
    CANCEL_POLICY = "CANCEL_POLICY"
    INSURANCE_QUERY = "INSURANCE_QUERY"
    FAREWELL = "FAREWELL"
    UNKNOWN = "UNKNOWN"


